### ISSUE TITLE
Regarding resnet32, BN init & non-linearity on the final particle concentration

### ISSUE THREAD

**Issue by sidml** [anilkagak2/PDE_GlobalLayer#2]
I had a few questions regarding the repo implementation:
1. Why is there an BN & activation after the final particle concentration ?
Refer [here](https://github.com/anilkagak2/PDE_GlobalLayer/blob/main/global_layer.py#L292). As per my understanding, iterating eq 4 of the paper should give us the final particle concentration. Eq 4 doesn't seem to have bn & relu non-linearity.
Perhaps I somehow missed this detail in the paper. If so, can you please provide a reference for it ?
2. In Table 3 of the paper it is mentioned that resnet32 has 460K params. However, according to the repo implementation it has more than 800K params. I think this is because of extra block here [resnet32](https://github.com/anilkagak2/PDE_GlobalLayer/blob/main/model.py#L216)
I think it should have been 
`  return _resnet('resnet32', BasicBlock, [m, m, m], pretrained, progress, global_ft = False,
                   **kwargs)`
([m, m, m] instead of [m, m, m, m])
3.  I think eps parameter of BN layer is being incorrectly initialized [here](https://github.com/anilkagak2/PDE_GlobalLayer/blob/main/global_layer.py#L181)

Thanks for you time & my apologies if I am misunderstanding something.

**Comment by anilkagak2** [comment]
Hi sidml, Thank you for your interest in the repository. Please find the answers below. 

1. Eq. 4 is very generic as it does not describe how (Dx, Dy) and (ux, uy) are constructed as well as the form of the function f. Its discrete implementation is indeed as is available in the global_layer.py .  Note that it is standard in conv blocks to include BN-Act after the layer is processed to improve the training time. Feel free to change this block as per your requirements, but note that BN-Act are applied only after K iterations of the PDE. 

2. The repo implementation of resnet is as per the original paper that had four stages. I believe the reason you are getting 800K params is due to the fact that the default number of filters in the resnet model is 64, 128, 128, 128. While the original paper has 16, 32, 64, 64. Please refer to the runner-cifar.sh for the exact instantation of various CIFAR baselines. In particular to reproduce the resnet32 baseline, please use 

```
CUDA_VISIBLE_DEVICES=$CUDA python train.py --data $DATA --model Resnet --dataset CIFAR-10 -m 5 --n1 16 --n2 32 --n3 64 --n4 64 -b 128  -o   -e $EPOCHS
CUDA_VISIBLE_DEVICES=$CUDA python train.py --data $DATA --model Resnet --dataset CIFAR-100 -m 5 --n1 16 --n2 32 --n3 64 --n4 64 -b 128  -o   -e $EPOCHS
```

3. I acknowedge that there was a bug in the BN layer used in global_layer.py. For this reason, for backward compatibility we added if/else block to use the incorrect eps initialization. I'm currently in the middle of reproducing these numbers for the correct eps parameter. The numbers seem to improve from the paper. We'll post once I'm able to run all the global experiments. In the meantime, to use the correct eps value, pass `use_diff_eps=False`
